export { default as Hero } from './Hero';
export { default as Sponsors } from './Sponsors';
export { default as About } from './About';
export { default as HowWorks } from './HowWorks';
export { default as ScrollTop } from './ScrollTop';
export { default as Features } from './Features';
export { default as Services } from './Services';
export { default as Cta } from './Cta';
export { default as Footer } from './Footer';
